spring.application.name=jobportal

# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:jobportaldb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.boot.autoconfigure=INFO

# Thymeleaf
spring.thymeleaf.cache=false

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vasudasari827@gmail.com
spring.mail.password=jdgv ttib twlk yrws
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# File upload (stub limits)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/resumes
